### ISSUE TITLE
Supporting the skip-lazy class

### ISSUE THREAD

**Issue by GermanKiwi** [WordPress/wp-lazy-loading#18]
In the original [WordPress ticket](https://core.trac.wordpress.org/ticket/44427) for adding lazy loading to core, there was some discussion about supporting a mechanism to allow theme or web developers skip adding the loading attribute for certain images, for example by adding the `skip-lazy` class or `data-skip-lazy` attribute, which are already widely used by other plugins.

However, it looks like this is currently not supported in version 1.0 of the Lazy Loading Feature Plugin.

Are there plans to add this functionality to this feature plugin, or to the Core implimentation, in the future? It would be greatly appreciated!

**Comment by chesio** [comment]
@GermanKiwi, see #4.
