### ISSUE TITLE
Review whether lazy-loading should cover more than images

### ISSUE THREAD

**Issue by felixarntz** [WordPress/wp-lazy-loading#3]
The [current version of the spec proposal](https://github.com/whatwg/html/pull/3752/files) does not include any information about `loading` becoming available on `iframe` tags. [Chrome _does_ support that](https://web.dev/native-lazy-loading/), but if that is even more experimental and not tied to the spec itself, we should not include it, especially as the primary focus certainly is images.

Let's gather some more information on this and revisit.

**Comment by remyperona** [comment]
There is a plan to update the spec for iframe too, but will be done separately, per comment https://github.com/whatwg/html/pull/3752#issuecomment-572174747

**Comment by azaozz** [comment]
Yes, that's my understanding too. Also the `auto` value for the `loading` attribute seems to have been dropped from the specs: https://github.com/whatwg/html/pull/3752/files#r344740202.

What would be best to do in WP in that case? Shall we keep the option to auto-add `loading="lazy"` to iframes, or shall we add it when the specs are ready (or nearly ready)?

Opened https://github.com/WordPress/wp-lazy-loading/issues/5 to follow up.

**Comment by felixarntz** [comment]
I've confirmed that inclusion of `iframe` tags is not planned in this iteration of the spec. It's likely coming in the future, but I think it makes sense for us to exclude iframes from here - especially since the impact of lazy-loading images will be much bigger.
